### ISSUE TITLE
2.5.3 not working with 1.27 (lergacy launcher install)

### ISSUE THREAD

**Issue by Tazzetiel** [ToniMacaroni/SaberFactory#150]
When using the newest (2.5.3) version of Saber Factory with game version 1.27 (installed via Legacy Launcher), the saber list page infinitely loads, while all other pages work perfectly fine for me. 

Reverting to 2.5.2 fixed it, so it for sure is something within the newest version specifically.

**Comment by ineverusegithub** [comment]
That would make since becuase 2.5.3 is for 1.28 if you read the release notes you would see that.

**Comment by Tazzetiel** [comment]
Yes, I am aware, I simply thought that it would still be backwards compatible, as it did not mention losing compatibility for previous versions anywhere. I guess i will have to live with that "update" notice in the GUI in game then, if this will not be "fixed" to work within backwards compatibility of even just 1 mayor version.

**Comment by ToniMacaroni** [comment]
Beat Saber 1.28 introduced a change in the base game lists which needed a change in SF. This also means that this version isn't compatible with earlier Beat Saber versions. 

With that being said, most SF versions aren't backwards compatible, since most of the time when an update drops, it's because SF needed a change for a new Beat Saber version.
